apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wercker-springboot
  labels:
   app: wercker-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wercker-springboot
  template:
    metadata:
      labels:
        app: wercker-springboot
    spec:
      containers:
      - name: wercker-springboot
        #image: registry.hub.docker.com/v2/georgexiang/wercker-springboot:latest
        image: ${DOCKER_REPO}:${WERCKER_GIT_COMMIT}
        ports:
        - containerPort: 8080  
      imagePullSecrets:
      - name:  ${OKE_IMAGESECRET}
---
apiVersion: v1
kind: Service
metadata:
  name: wercker-springboot
spec:
  type: LoadBalancer
  ports:
  - port: 8080 
    targetPort: 8080
  selector:
    app: wercker-springboot